version: '3.8'

services:
  web:
    build: .
    image: lead
    container_name: lead_con
    restart: always
    command: 'sh -c "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8003"'
    ports:
      - '8003:8003'
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: pg6
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
